#!/usr/bin/env bash
# Verify that generated/base_client.py is in sync with the hand-written base_client.py.
# The generated copy has a 2-line header ("# Generated by ariadne-codegen\n") that we skip.
set -euo pipefail

if ! diff <(tail -n +3 deezer_python_gql/generated/base_client.py) deezer_python_gql/base_client.py > /dev/null 2>&1; then
    echo "ERROR: generated/base_client.py is out of sync with base_client.py"
    echo "Run 'make codegen' to regenerate."
    exit 1
fi
